version: '3.8'

networks:
  k6:
  grafana:
  timescaledb:

services:
  timescaledb:
    image: timescale/timescaledb:${TIMESCALEDB_VERSION}
    command: postgres -c shared_preload_libraries=timescaledb
    networks:
      - k6
      - grafana
      - timescaledb
    ports:
      - "${TIMESCALEDB_PORT}:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=k6
      - POSTGRES_USER=k6
      - POSTGRES_PASSWORD=k6
       
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    networks:
      - grafana
      - timescaledb
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ${GRAFANA_DATA}:/etc/grafana/provisioning/
