version: '3.8'

networks:
  grafana:
  timescaledb:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ".data-docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - ".data-docker/prometheus/rules.yml:/etc/prometheus/rules.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - localprom
    ports:
      - 9100:9100
  
  alert-manager:
    image: prom/alertmanager:latest
    volumes:
      - ".data-docker/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - localprom
    ports:
      - 9093:9093
 
       
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    networks:
      - grafana
      - timescaledb
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ${GRAFANA_DATA}:/etc/grafana/provisioning/

  networks:
    localprom:
      driver: bridge